feat: introduce `cargo-deny` and `cargo-about`
This ensures not only that the dependencies we use are licensed
according to what we require, but also helps us generate a valid file
that contains all necessary attributions to the third-parties whose
works we make use of.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,6 +18,42 @@ jobs:
       run: |
         ./.tools/check-license-comments.sh
 
+  cargo-deny:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        checks:
+        - advisories
+        - bans licenses sources
+
+    # Prevent sudden announcement of a new advisory from failing ci:
+    continue-on-error: ${{ matrix.checks == 'advisories' }}
+
+    steps:
+    - uses: actions/checkout@v4
+    - uses: EmbarkStudios/cargo-deny-action@v2.0.1
+      with:
+        command: check ${{ matrix.checks }}
+
+  cargo-about:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+    - name: Install cargo-about
+      uses: taiki-e/install-action@v2.44.50
+      with:
+        tool: cargo-about
+    - name: Generate up-to-date `THIRD_PARTY_LICENSES.md`
+      run: cargo about generate -o ./THIRD_PARTY_LICENSES.md ./.tools/cargo-about-markdown-template.hbs
+    - name: Verify `THIRD_PARTY_LICENSES.md` is up-to-date
+      run: |
+        git diff --exit-code --quiet ./THIRD_PARTY_LICENSES.md
+        if [ $? -ne 0 ]; then
+          echo "THIRD_PARTY_LICENSES.md is out of date. Please run 'cargo about generate -o ./THIRD_PARTY_LICENSES.md ./.tools/cargo-about-markdown-template.hbs' locally, compare what has changed and commit the changes."
+          exit 1
+        fi
+
   linting:
     permissions:
       contents: read
